import java.util.Scanner;

public class IncomeTaxCalculator {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        TaxTableTools taxTool = new TaxTableTools();

        // Salary bounds and tax rates (as defined)
        int[] salaryBounds = {0, 20000, 50000, 100000, Integer.MAX_VALUE};
        double[] taxRates = {0.0, 0.10, 0.20, 0.30, 0.40};

        taxTool.setTaxTable(salaryBounds, taxRates);

        while (true) {
            System.out.print("Enter annual income (-1 to exit): ");
            int income = scanner.nextInt();

            if (income == -1) {
                break;
            } else if (income < 0) {
                System.out.println("Invalid input. Please enter a positive number or -1 to exit.");
                continue;
            }

            taxTool.setSalary(income);
            double rate = taxTool.getTaxRate();
            double tax = taxTool.calculateTax();

            System.out.printf("Annual Income: %d Tax rate: %.2f Tax to pay: %.2f%n", income, rate, tax);
        }

        scanner.close();
    }
}
