public class TaxTableTools {
    private int[] salaryBounds;
    private double[] taxRates;
    private int salary;

    // Setter for salary and tax rate tables
    public void setTaxTable(int[] salaryBounds, double[] taxRates) {
        this.salaryBounds = salaryBounds;
        this.taxRates = taxRates;
    }

    // Setter for the salary
    public void setSalary(int salary) {
        this.salary = salary;
    }

    // Method to get the tax rate for the current salary
    public double getTaxRate() {
        for (int i = 0; i < salaryBounds.length - 1; i++) {
            if (salary >= salaryBounds[i] && salary < salaryBounds[i + 1]) {
                return taxRates[i];
            }
        }
        return taxRates[taxRates.length - 1]; // max rate
    }

    // Method to calculate tax
    public double calculateTax() {
        return salary * getTaxRate();
    }
